### ISSUE TITLE
How to close highlight  or review? Thanks a lot ,thank you again!

### ISSUE THREAD

**Issue by baelow** [ec-jrc/jrc-proofreading#1]
This macro is really great. I would like to ask how to turn off the reviewing mode and highlighting after revision? It may be even better to not have reviewing and highlighting when dealing with a line of text chemical expression. Thank you!

**Comment by anderdd-22** [comment]
Hello, sorry for the late reply. I just saw your comment today. I have modified my notification settings so this doesn't happen again. Thanks for your suggestions. Indeed, the final message box was intended for large documents, and it does not make sense when formatting short lines of text. I have added that the final message box is only shown if the selected text is more than 1,000 characters. 
Regarding the highlighting, I have left this on as the default behaviour, but I have added a switch to stop highlighting if you prefer. In the code there is a line "HighlightFormulae = True". If you want to stop highlighting completely, just replace it with "HighlightFormulae = False."
Latest version of the code with these changes is uploaded (v.2.6).

**Comment by anderdd-22** [comment]
I realise that with "reviewing mode" you probably meant "tracked changes".
I have added a switch for tracked changes: TrackChanges = True
To deactivate, replace with: TrackChanges = False
Uploaded as version v.2.7

**Comment by baelow** [comment]
The latest version is impeccable and fully meets my requirements. Thank you.😆

**Comment by baelow** [comment]
> I realise that with "reviewing mode" you probably meant "tracked changes". I have added a switch for tracked changes: TrackChanges = True To deactivate, replace with: TrackChanges = False Uploaded as version v.2.7

The latest version is impeccable and fully meets my requirements. Thank you.😆
